Add zero-shot visual prompting task (#2834)
* Add entities

* Add models

* Add configs & recipes

* Add LitModule

* Add dataset

* Fix to resize bboxes

* Update cores

* Enable to load checkpoint & fix layers

* Enable training

* Align params with 1.x

* Add PerturbBoundingBoxes

* Support multiple metrics

* Update config & recipe

* Update scheduler

* Update for the latest commit

* Update config

* Update early stopping

* Fix PerturbBoundingBoxes

* (WIP) Add unit tests

* Fix

* Fix data pipeline

* Fix to use num_masks

* Update to use torchmetric

* Fix tiny vit

* Fix unit test

* Fix

* (WIP) Add tvt pipeline

* pre-commit

* Add integration test

* Fix metrics

* Fix

* Enabel tvt pipeline

* pre-commit

* Fix intg test

* Update to the latest commit

* Fix to reuse inference step

* pre-commit

* Add regressions test

* Fix to implicitly use `config` in OTXModel

* Fix unit test

* Update torchvision pipeline

* pre-commit

* (WIP) Add zero shot

* Update config & recipe

* Fix typo

* Fix regression test

* Add `ResizeToLongestEdge` for square image & refactoring

* Add `Points` tensor & update data entity

* Add `Points` in transform

* Update `OTXVisualPromptingDataset`

* Add `custom_wrap` to add `Points`

* Update `use_bbox` and `use_point` in factory

* Update config

* Divide prompts into bboxes and points again

* Fix

* Update unit test

* Remove `include_polygons` & Add aligning gt_masks

* Update SAM forward pipeline

* Update tests

* Update tests for mmdet

* precommit

* Disable deterministic
RuntimeError: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also
file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

* Update config

* Update num_workers

* (WIP) Update zero-shot

* (WIP) Add zero shot visual prompting

* Normalize fine tuning

* Add forward for inference

* Update configs

* Set dataset and module

* Divide forward type into finetuning, learn, and infer

* (WIP) Add `learn`

* Enable to save ref info into checkpoitn

* Update initialization part

* Enable to load checkpoint

* Add `infer`

* Enclose `postprocess_masks` in `forward`

* Fix warning

* Fix

* Fix unit tests

* Fix

* Enable setting default config & fix `used_indices`

* Patch `query_size`

* Restore

* Fix type

* Add unit tests

* precommit

* Fix #preds and #target differ

* Fix for unused label

* Add intg test

* precommit

* precommit

* Fix intg test

* Add fixture

* Add reset train_metric

* Fix intg test

* Add default config classes

* Move `state_dict` and `load_state_dict` into model

* Fix unit test

* Wrap reference infos with `ParameterDict`

* precommit

* Apply autoconfig to zsl

* Fix autoconfig intg test

* Add types

* Fix intg test